ICP-1

1) Please click on the link to download ICP1 and open it in google colab: ICP 1 Source code LinkLinks to an external site.

2) Run the code and understand the different operations performed on the dataset.

3) Replace the missing values in numeric columns of  dataset (hepatitis dataset) with the mean values of the column.

4) Submit your ICP before the midnight (clearly showing the step where you replaced the missing values with the mean of those columns).  Upload your source file to GitHub and share the link on Canvas.

import libraries such as numpy and pandas

In [1]:
import pandas as pd
import numpy as np

Loading the dataset

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/datasets/hepatitis/master/data/hepatitis.csv')
df.head(10)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live

displaying first 15rows

In [4]:
df.head(15)

,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class
0,30,male,False,False,False,False,False,False,False,False,False,False,False,1.0,85.0,18.0,4.0,NaN,False,live
1,50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135.0,42.0,3.5,NaN,False,live
2,78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96.0,32.0,4.0,NaN,False,live
3,31,female,NaN,True,False,False,False,True,False,False,False,False,False,0.7,46.0,52.0,4.0,80.0,False,live
4,34,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,200.0,4.0,NaN,False,live
5,34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95.0,28.0,4.0,75.0,False,live
6,51,female,False,False,True,False,True,True,False,True,True,False,False,NaN,NaN,NaN,NaN,NaN,False,die
7,23,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,NaN,NaN,NaN,False,live
8,39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,NaN,48.0,4.4,NaN,False,live
9,30,female,True,False,False,False,False,True,False,False,False,False,False,1.0,NaN,120.0,3.9,NaN,False,live
10,39,female,False,True,False,False,False,False,True,False,False,False,False,1.3,78.0,30.0,4.4,85.0,False,live
11,32,female,True,True,True,False,False,True,True,False,True,False,False,1.0,59.0,249.0,3.7,54.0,False,live
12,41,female,True,True,True,False,False,True,True,False,False,False,False,0.9,81.0,60.0,3.9,52.0,False,live
13,30,female,True,False,True,False,False,True,True,False,False,False,False,2.2,57.0,144.0,4.9,78.0,False,live
14,47,female,False,True,False,False,False,True,False,False,False,False,False,NaN,NaN,60.0,NaN,NaN,False,live

Getting all numeric values columns

In [6]:
numeric_df = df.select_dtypes(include=np.number).copy()
numeric_df

     age  bilirubin  alk_phosphate   sgot  albumin  protime
0     30        1.0           85.0   18.0      4.0      NaN
1     50        0.9          135.0   42.0      3.5      NaN
2     78        0.7           96.0   32.0      4.0      NaN
3     31        0.7           46.0   52.0      4.0     80.0
4     34        1.0            NaN  200.0      4.0      NaN
..   ...        ...            ...    ...      ...      ...
150   46        7.6            NaN  242.0      3.3     50.0
151   44        0.9          126.0  142.0      4.3      NaN
152   61        0.8           75.0   20.0      4.1      NaN
153   53        1.5           81.0   19.0      4.1     48.0
154   43        1.2          100.0   19.0      3.1     42.0

[155 rows x 6 columns]

Checking for missing values in numeric data set

In [7]:
numeric_df.isnull().sum()

age               0
bilirubin         6
alk_phosphate    29
sgot              4
albumin          16
protime          67
dtype: int64

Calculation mean for each column

In [8]:
numeric_df.mean()

age               41.200000
bilirubin          1.427517
alk_phosphate    105.325397
sgot              85.894040
albumin            3.817266
protime           61.852273
dtype: float64

Replacing missing values with mean for numeric dataframe

In [11]:
numeric_df.fillna(numeric_df.mean(), inplace=True)
numeric_df.isnull().sum()

age              0
bilirubin        0
alk_phosphate    0
sgot             0
albumin          0
protime          0
dtype: int64

In [12]:
numeric_df

     age  bilirubin  alk_phosphate   sgot  albumin    protime
0     30        1.0      85.000000   18.0      4.0  61.852273
1     50        0.9     135.000000   42.0      3.5  61.852273
2     78        0.7      96.000000   32.0      4.0  61.852273
3     31        0.7      46.000000   52.0      4.0  80.000000
4     34        1.0     105.325397  200.0      4.0  61.852273
..   ...        ...            ...    ...      ...        ...
150   46        7.6     105.325397  242.0      3.3  50.000000
151   44        0.9     126.000000  142.0      4.3  61.852273
152   61        0.8      75.000000   20.0      4.1  61.852273
153   53        1.5      81.000000   19.0      4.1  48.000000
154   43        1.2     100.000000   19.0      3.1  42.000000

[155 rows x 6 columns]